### ISSUE TITLE
option to output metadata for the detected fusions 

### ISSUE THREAD

**Issue by shernadi** [vpc-ccg/genion#2]
Hi, 

I have analysed some data using Genion lately and although the analysis finished quite smoothly I was wondering if there is an easy way to get Genion to include bit more details in the output table or maybe to a log file regarding the detected fusions? I think it would be quite useful to have some info on things such as supporting-read IDs, chromosome locations with position of the breakpoints in the genome to make the evaluation process a bit easier. 

Many Thanks!

**Comment by f0t1h** [comment]
Thank you for the feedback. I will prepare an update to print detailed logs.

**Comment by shernadi** [comment]
Hi, 

Thank you for including the additional data into the outputs so quickly, I found them really useful! I am not sure if it is related but I am experiencing sum issues when analysing the same samples with the new version though (interestingly only with some of the samples), where I am getting the following error: 

```
genion: src/annotate.cpp:204: void annotate::interval::extend(const annotate::interval&): Assertion `reverse_strand == other.reverse_strand' failed.
--
```
(I am using minimap2 to generate the alignments) 
 
Many Thanks!

**Comment by f0t1h** [comment]
Can you let me know, which gene annotation are you using for the run? That error should only raise when a gene has exons on different strands. I will look in detail to see if it is something else.

**Comment by f0t1h** [comment]
OK, I forgot about palindromic reads when I put that assertion. I removed it in the latest update, since palindromic reads shouldn't raise any problems on the current breakpoint calculation. If you are using bioconda, it should update soon as well.
