### ISSUE TITLE
genion 1.1.1 installed by conda returns version string 1.1.0

### ISSUE THREAD

**Issue by james-vincent** [vpc-ccg/genion#4]
Install of genion with specific version:

mamba install genion=1.1.1 -c bioconda

installs a binary that give version string 1.1.0:

```
 $ ./genion -v
1.1.0
```

**Comment by f0t1h** [comment]
Thank you for letting me know. I forgot to update the version string, it should be 1.1.1. I will make the versioning automatic in future updates.
